package(default_visibility = ["//visibility:public"])

filegroup(
    name = "test_data",
    srcs = [
        "traffic.mp4",
        "yolov8m-oiv7.onnx",
        "yolov8m.onnx",
        "yolov8n.onnx",
        "test.jpg",
    ],
)
