load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "traffic_timing_decision_core",
    srcs = [
        "src/common.cpp",
        "src/decision_engine.cpp",
        "src/health_reporter.cpp",
        "src/periodic_service.cpp",
        "src/timing_plan_publisher.cpp",
        "src/traffic_data_receiver.cpp",
    ],
    hdrs = glob(["include/*.h"]),
    copts = [
        "-Wall",
        "-Wextra",
        "-Wpedantic",
    ],
    local_defines = ["DECISION_ENGINE_STAT"],
    includes = ["include"],
    deps = [
        "//ipc:traffic_ipc",
        "@score_baselibs//score/mw/log:frontend",
        "@score_lifecycle//score/health_monitor:health_monitoring_cc",
    ],
)

cc_library(
    name = "traffic_timing_decision_application",
    srcs = [
        "src/timing_decision_application.cpp",
        "src/timing_report_logger.cpp",
    ],
    hdrs = [
        "include/timing_decision_application.h",
        "include/timing_report_logger.h",
    ],
    deps = [
        ":traffic_timing_decision_core",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/mw/log/configuration",
        "@score_baselibs//src/log/stdout_logger_cpp_init",
        "@score_logging//score/mw/log/backend:file",
        "@score_lifecycle//score/launch_manager:lifecycle_cc",
    ],
)

cc_binary(
    name = "traffic_timing_decision",
    srcs = ["src/main.cpp"],
    linkopts = select({
        "@platforms//os:linux": [
            "-lpthread",
            "-lrt",
        ],
        "//conditions:default": [],
    }),
    deps = [
        ":traffic_timing_decision_application",
        "@score_lifecycle//score/launch_manager:lifecycle_cc",
    ],
)

cc_binary(
    name = "decision_demo",
    srcs = ["src/decision_demo.cpp"],
    deps = [
        ":traffic_timing_decision_core",
        "@score_baselibs//score/mw/log",
    ],
)

cc_binary(
    name = "analytics",
    srcs = [
        "include/analytics.h",
        "src/analytics.cpp",
    ],
    copts = [
        "-D_GNU_SOURCE",
        "-Wall",
        "-Wextra",
        "-Wpedantic",
    ],
    data = [
        "output/execution_time.txt",
        "output/wakeup_latency.txt",
    ],
    includes = ["include"],
)
