load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "signal_control_application",
    srcs = ["src/signal_control_application.cpp"],
    hdrs = glob(["include/*.h"]),
    copts = [
        "-Wall",
        "-Wextra",
        "-Wpedantic",
    ],
    includes = ["include"],
    deps = [
        "//ipc:traffic_ipc",
        "//common:absolute_periodic",
        "//common:periodic_health_reporter",
        "@score_baselibs//score/mw/log:frontend",
        "@score_lifecycle//score/launch_manager:lifecycle_cc",
    ],
)

cc_binary(
    name = "signal_control_demo",
    srcs = ["src/main.cpp"],
    deps = [
        ":signal_control_application",
        "@score_baselibs//score/mw/log",
        "@score_lifecycle//score/launch_manager:lifecycle_cc",
    ],
)
