load("@score_lifecycle//:defs.bzl", "launch_manager_config")

package(default_visibility = ["//visibility:public"])

exports_files([
    "ecu_logging_config.json",
    "hm_logging.json",
    "logging.json",
    "perception_logging.json",
    "signal_control_logging.json",
    "timing_decision_logging.json",
    "traffic_light_lifecycle.json",
    "traffic_perception_config.json",
])

launch_manager_config(
    name = "traffic_light_lifecycle_config",
    config = ":traffic_light_lifecycle.json",
    flatbuffer_out_dir = "etc",
)
