load("@score_lifecycle//:defs.bzl", "launch_manager_config")

package(default_visibility = ["//visibility:public"])

exports_files([
    "ecu_logging_config.json",
    "hm_logging.json",
    "logging.json",
    "traffic_signal_controller_lifecycle.json",
])

launch_manager_config(
    name = "traffic_signal_controller_lifecycle_config",
    config = ":traffic_signal_controller_lifecycle.json",
    flatbuffer_out_dir = "etc",
)
