sh_binary(
    name = "traffic_signal_controller_system",
    srcs = ["run_traffic_signal_controller.sh"],
    args = [
        # $1: Launch Manager binary
        "$(rlocationpath @score_lifecycle//score/launch_manager:launch_manager)",

        # $2: Control daemon binary
        "$(rlocationpath //control_daemon:control_daemon)",

        # $3: Lifecycle control utility
        "$(rlocationpath //control_daemon:lmcontrol)",

        # $4: Traffic signal controller binary
        "$(rlocationpath //traffic_signal_controller:traffic_signal_controller)",

        # $5: Generated lifecycle configuration
        "$(rlocationpath //config:traffic_signal_controller_lifecycle_config)",

        # $6: ECU logging configuration
        "$(rlocationpath //config:ecu_logging_config.json)",

        # $7: Health Manager logging configuration
        "$(rlocationpath //config:hm_logging.json)",

        # $8: Launch Manager logging configuration
        #
        # Tạm thời dùng chung logging.json.
        "$(rlocationpath //config:logging.json)",

        # $9: Traffic Signal Controller logging configuration
        "$(rlocationpath //config:logging.json)",
    ],
    data = [
        "//traffic_signal_controller:traffic_signal_controller",

        "//config:ecu_logging_config.json",
        "//config:hm_logging.json",
        "//config:logging.json",
        "//config:traffic_signal_controller_lifecycle_config",

        "//control_daemon:control_daemon",
        "//control_daemon:lmcontrol",

        "@bazel_tools//tools/bash/runfiles",
        "@score_lifecycle//score/launch_manager:launch_manager",
    ],
    visibility = ["//visibility:public"],
)