workspace(name = "traffic_perception")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "nlohmann_json",
    urls = [
        "https://github.com/nlohmann/json/releases/download/v3.12.0/json.tar.xz",
    ],
    sha256 = "d3c8b06d5fb2aab77b66c67b8c6d0bde32e8e5d7795cfb79cb58f0a2f9d3d1f9",
    strip_prefix = "json-3.12.0",
    build_file_content = """
cc_library(
    name = "json",
    hdrs = glob(["single_include/**/*.hpp"]),
    includes = ["single_include"],
    visibility = ["//visibility:public"],
)
""",
)

new_local_repository(
    name = "opencv",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "opencv",
    hdrs = glob([
        "include/opencv4/opencv2/**/*.hpp",
        "include/opencv4/opencv2/**/*.h",
    ]),
    includes = ["include/opencv4"],
    linkopts = [
        "-lopencv_core",
        "-lopencv_video",
        "-lopencv_imgproc",
        "-lopencv_highgui",
        "-lopencv_videoio",
    ],
    visibility = ["//visibility:public"],
)
""",
)

new_local_repository(
    name = "onnxruntime",
    path = "/opt/onnxruntime",
    build_file_content = """
cc_library(
    name = "onnxruntime",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    linkopts = [
        "-L/opt/onnxruntime/lib",
        "-lonnxruntime",
        "-Wl,-rpath,/opt/onnxruntime/lib",
    ],
    visibility = ["//visibility:public"],
)
""",
)
