#ifndef ANALYTICS_H
#define ANALYTICS_H

#include <string>
#include <vector>
#include <cstdint>

#include <common/config.h>

class Analytics {
 public:
  explicit Analytics(std::string logFilePath);

  bool Analyze();
  bool WriteReport(const std::string& outputPath) const;

 private:
  enum class EventType {
    Unknown,
    Started,
    Stopped,
    PhaseStatus,
    PlanReceived,
    PlanValidated,
    PlanRejected,
    PlanPublished,
    PlanApplied,
    EmergencyReceived,
    EmergencyAccepted,
    EmergencyRejected,
    EmergencyApplied,
    FsmTick
  };

  struct LogEntry {
    // Metadata generated by S-CORE logging.
    std::string date;
    std::string time;
    std::string ecuId;
    std::string applicationId;
    std::string contextId;
    std::string logLevel;

    // Original message generated by the application.
    std::string message;

    // Parsed application data.
    EventType eventType{EventType::Unknown};
    std::string phase;
    std::uint32_t remainingTimeMs{};
    std::uint32_t planId{};

    std::uint64_t expectedTimestampNs{};
    std::uint64_t actualTimestampNs{};
    std::uint64_t executionTimeNs{};

    std::string result;
    std::string rejectReason;
  };

  bool LoadLog();
  bool ParseLogLine(const std::string& line, LogEntry& entry) const;
  void ParseApplicationMessage(LogEntry& entry) const;

  void ComputePhaseStatistics();
  void ComputePlanStatistics();
  void ComputeEmergencyStatistics();
  void ComputeRealTimeStatistics();

  std::string logFilePath_;
  std::vector<LogEntry> logEntries_;
};

#endif
