sh_binary(
    name = "traffic_light_system",
    srcs = ["run_traffic_light_system.sh"],
    args = [
        "$(rlocationpath @score_lifecycle//score/launch_manager:launch_manager)",
        "$(rlocationpath //control_daemon:control_daemon)",
        "$(rlocationpath //control_daemon:lmcontrol)",
        "$(rlocationpath //perception_demo:perception_demo)",
        "$(rlocationpath //traffic_timing_decision:traffic_timing_decision)",
        "$(rlocationpath //signal_control_demo:signal_control_demo)",
        "$(rlocationpath //ipc:ipc_reset)",
        "$(rlocationpath //config:traffic_light_lifecycle_config)",
        "$(rlocationpath //config:ecu_logging_config.json)",
        "$(rlocationpath //config:hm_logging.json)",
        "$(rlocationpath //config:logging.json)",
        "$(rlocationpath //config:perception_logging.json)",
        "$(rlocationpath //config:timing_decision_logging.json)",
        "$(rlocationpath //config:signal_control_logging.json)",
    ],
    data = [
        "//config:traffic_light_lifecycle_config",
        "//config:ecu_logging_config.json",
        "//config:hm_logging.json",
        "//config:logging.json",
        "//config:perception_logging.json",
        "//config:signal_control_logging.json",
        "//config:timing_decision_logging.json",
        "//control_daemon:control_daemon",
        "//control_daemon:lmcontrol",
        "//ipc:ipc_reset",
        "//perception_demo:perception_demo",
        "//signal_control_demo:signal_control_demo",
        "//traffic_timing_decision:traffic_timing_decision",
        "@bazel_tools//tools/bash/runfiles",
        "@score_lifecycle//score/launch_manager:launch_manager",
    ],
    visibility = ["//visibility:public"],
)
