sh_binary(
    name = "traffic_light_system",
    srcs = ["run_traffic_light_system.sh"],
    args = [
        "$(rlocationpath @score_lifecycle//score/launch_manager:launch_manager)",
        "$(rlocationpath //control_daemon:control_daemon)",
        "$(rlocationpath //control_daemon:lmcontrol)",
        "$(rlocationpath //traffic_perception:traffic_perception)",
        "$(rlocationpath //traffic_timing_decision:traffic_timing_decision)",
        "$(rlocationpath //traffic_signal_controller:traffic_signal_controller)",
        "$(rlocationpath @traffic_ipc//:ipc_reset)",
        "$(rlocationpath //config:traffic_light_lifecycle_config)",
        "$(rlocationpath //config:ecu_logging_config.json)",
        "$(rlocationpath //config:hm_logging.json)",
        "$(rlocationpath //config:logging.json)",
        "$(rlocationpath //config:perception_logging.json)",
        "$(rlocationpath //config:timing_decision_logging.json)",
        "$(rlocationpath //config:signal_control_logging.json)",
        "$(rlocationpath //traffic_perception/lib/onnxruntime:onnxruntime_runtime)",
        "$(rlocationpath //config:traffic_perception_config.json)",
        "$(rlocationpath //data:yolov8m-oiv7.onnx)",
        "$(rlocationpath //data:yolov8n.onnx)",
        "$(rlocationpath //data:traffic.mp4)",
        "$(rlocationpath //data:traffic2.mp4)",
        "$(rlocationpath //data:traffic3.mp4)",
        "$(rlocationpath //data:traffic4.mp4)",
    ],
    data = [
        "//config:traffic_light_lifecycle_config",
        "//config:ecu_logging_config.json",
        "//config:hm_logging.json",
        "//config:logging.json",
        "//config:perception_logging.json",
        "//config:signal_control_logging.json",
        "//config:timing_decision_logging.json",
        "//config:traffic_perception_config.json",
        "//control_daemon:control_daemon",
        "//control_daemon:lmcontrol",
        "@traffic_ipc//:ipc_reset",
        "//traffic_perception:traffic_perception",
        "//traffic_perception/lib/onnxruntime:onnxruntime_runtime",
        "//traffic_signal_controller:traffic_signal_controller",
        "//traffic_timing_decision:traffic_timing_decision",
        "//data:yolov8m-oiv7.onnx",
        "//data:yolov8n.onnx",
        "//data:traffic.mp4",
        "//data:traffic2.mp4",
        "//data:traffic3.mp4",
        "//data:traffic4.mp4",
        "@bazel_tools//tools/bash/runfiles",
        "@score_lifecycle//score/launch_manager:launch_manager",
    ],
    visibility = ["//visibility:public"],
)
